[feat] Scaffolding for the charm
canonical/vault-operator pull request #2
Opened 2023-10-03 21:52 UTC by gruyaume

## Overview

This PR includes scaffolding for the charm.

Note: This PR intentionally excludes publishing at the moment since we will need a new track in Charmhub for this new generation of the charm.

2023-10-03 23:14 UTC, ghislainbourgeois requested changes
Small detail to fix, otherwise LGTM

2023-10-03 23:14 UTC, ghislainbourgeois commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Kubernetes version [e.g. 1.22]
```suggestion
```

2023-10-04 04:47 UTC, saltiyazan approved these changes

2023-10-04 12:34 UTC, ghislainbourgeois approved these changes

2023-10-04 12:53 UTC, merged