fix: Access kv secret using secret ID
canonical/vault-operator pull request #255
Opened 2024-07-30 10:23 UTC by saltiyazan

# Description

Not to lose the secret://modeluuid/standard_secret_id format of the secret ID which is required to access the secret in cross model relations we get the secret with the secret ID that was initially returned by add_secret and initially stored in the relation databag.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-30 12:06 UTC, gruyaume commented
Is this a duplicate of #254?

2024-07-30 12:09 UTC, saltiyazan commented
> Is this a duplicate of #254?

Backporting to `release-1.15`

2024-07-30 13:37 UTC, gruyaume commented
> > Is this a duplicate of #254?
> 
> Backporting to `release-1.15`

Oops my bad

2024-07-30 16:44 UTC, DanielArndt requested changes
Since, intuitively, one would expect the old code to work, I think we need one of two things (or both):

1. a test that ensures this behaviour doesn't change (i.e. that the id is always provided when we update the secret, or 
2. a comment that warns us not to remove this ID in the future, until the issue has been fixed on the Juju side. Probably, also, a reference to the Juju bug.

2024-07-31 15:17 UTC, DanielArndt approved these changes

2024-07-31 15:18 UTC, merged