feat: Implements tls in the charm using vault_tls lib
canonical/vault-operator pull request #40
Opened 2024-02-07 09:55 UTC by saltiyazan

# Description

 Implements tls in the charm using vault_tls lib

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-02-19 13:06 UTC, gruyaume requested changes

2024-02-19 13:06 UTC, gruyaume commented on tests/integration/test_integration.py
>      client = hvac.Client(url=vault_endpoint, verify=False)
We shouldn't need the `verify=False` now

2024-02-19 13:06 UTC, gruyaume commented on charmcraft.yaml
> +      - cryptography
No need to add this here since we added `rustc` and the others, we should be able to build it.

2024-02-19 14:47 UTC, Kayra1 approved these changes
Looks like we didn't have to duplicate pretty much anything related to TLS. Great job.

2024-02-19 14:47 UTC, Kayra1 commented on tests/unit/test_charm.py
> +        """Set the certificate secret in the peer relation."""
Did this docstring come from the copy paste? Should change it here and there if so.

2024-02-20 18:42 UTC, gruyaume approved these changes

2024-02-21 05:52 UTC, merged